services:

  zcash-client:
    image: zcash
    container_name: zcash
    hostname: zcash
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./data/:/opt/graphsense/data
    networks:
      - graphsense-net
    ports:
      - 8632:8632
    restart: always

networks:
  graphsense-net:
    name: graphsense-net
